### ISSUE TITLE
Support Features rendering / static/unmount props

### ISSUE THREAD

**Issue by rgossiaux** [rgossiaux/svelte-headlessui#1]

**Comment by vhscom** [comment]
Should we expect to see `static` and `unmount` appear in the completions dialog with this issue closed?

<img width="591" alt="Screen Shot 2022-04-19 at 10 53 26 PM" src="https://user-images.githubusercontent.com/97140109/164033080-b03aff99-924a-45f1-b78c-2dd9568198d1.png">
