### ISSUE TITLE
Unable to use with sveltekit

### ISSUE THREAD

**Issue by sharmapukar217** [rgossiaux/svelte-headlessui#106]
Directory import 'node_modules/svelte-headlessui/components/dialog' is not supported resolving ES modules imported from node_modules/svelte-headlessui/index.js

**Comment by organetto8** [comment]
Did you find a solution?

**Comment by organetto8** [comment]
> Oh yes.... 😀

which one lol?

**Comment by sharmapukar217** [comment]
I didn't understand??

**Comment by organetto8** [comment]
How did you solved the problem?

**Comment by sharmapukar217** [comment]
Oh.. i was using npm alias which seems to break the ssr build so i added my aliased name to svelte.kit.ssr 😃

**Comment by cwygoda** [comment]
I'm in the same situation, can you tell more in detail, @sharmapukar217, please?

**Comment by sharmapukar217** [comment]
> I'm in the same situation, can you tell more in detail, @sharmapukar217, please?

are you trying to use this package with alias name??

**Comment by sharmapukar217** [comment]
For those who are trying to use aliased name for the package and having error with sveltekit, use: supposing the aliased name is `svelte-headlessui`
```js
/** @type {import('vite').UserConfig} */
const config = {
  plugins: [sveltekit()],
  ssr: { noExternal: ["svelte-headlessui"] }
};`
