### ISSUE TITLE
Add props for Dialog to disable Escape to close and click overlay to close

### ISSUE THREAD

**Issue by futantan** [rgossiaux/svelte-headlessui#116]
When we need user to confirm from two dangerous options, he/she must select from these options, how about add two props:
- `closeOnEsc` default `true`
- `closeOnOverlayClick` default `true`

Just like https://chakra-ui.com/docs/components/modal/props

**Comment by futantan** [comment]
Willing to help if this proposal is approved

**Comment by rgossiaux** [comment]
I can understand the motivation behind this, but this library is a port of headlessui and there are no plans to add more functionality beyond what exists in that library. Keeping up with upstream is a tough enough challenge by itself. Sorry!
