### ISSUE TITLE
Can't bind popover's "open" prop to a boolean

### ISSUE THREAD

**Issue by touficbatache** [rgossiaux/svelte-headlessui#153]
**Describe the bug**
Can't bind a popover's `open` prop to a boolean in order to keep track of the open and closed states.

**To Reproduce**
```
<script lang="ts">
  let isPopoverOpen = false
</script>

<Popover bind:open={isPopoverOpen}>
   ...
</Popover>
```
doesn't work.

**Library version**
2.0.0

**Comment by rgossiaux** [comment]
`<Popover>` doesn't have an `open` prop, I recommend going back to the docs: https://svelte-headlessui.goss.io/docs/2.0/popover#showinghiding-the-popover
