### ISSUE TITLE
Better error messages on React-style props

### ISSUE THREAD

**Issue by rgossiaux** [rgossiaux/svelte-headlessui#24]
Something I've been thinking about recently--it would be nice if I could add in some error messages if you use React-style prop names (className, onChange, htmlFor, and some SVG attributes come to mind). Ideally I can get these to throw a type error, but even a compile or runtime error will make it a lot friendlier for people porting React code (ie users of Tailwind UI).

**Comment by vhscom** [comment]
So long as the error doesn't throw up a redbox. I'd find that aggravating personally if I had to stop what I was doing before I can see the result on the screen. Perhaps there's a linter for this?

**Comment by vhscom** [comment]
So long as the error doesn't throw up a redbox. I'd find that aggravating personally if I had to stop what I was doing before I can see the result on the screen.

**Comment by vhscom** [comment]
So long as the error doesn't throw up a redbox. I'd find that aggravating personally if I had to stop what I was doing before I could see the result on the screen.

**Comment by rgossiaux** [comment]
Related to #43 which will probably solve this sufficiently (as long as you're using TS--I think that's a reasonable constraint).
