### ISSUE TITLE
Unused export properties warnings from vite-plugin-svelte

### ISSUE THREAD

**Issue by franzvezuli** [rgossiaux/svelte-headlessui#25]
I am seeing these warning logs at first load.

Forgive my ignorance, am new to front end dev, and also both to `Sveltekit` and `Vite`. Is it important for `vite-plugin-svelte` to care about `node_modules` or should it ignore everything except what's in my `src` folder?

```
yarn run v1.22.15
$ svelte-kit dev --host 0.0.0.0
Pre-bundling dependencies:
  svelte/store
  svelte
  svelte-hero-icons
  svelte/animate
  svelte/easing
  (...and 3 more)
(this will be run only when your dependencies or config have changed)

  SvelteKit v1.0.0-next.202

  local:   http://localhost:3000
  network: http://172.18.0.2:3000

  Note that all files in the following directories will be accessible to anyone on your network: static, src/lib, src/routes, src, .svelte-kit, node_modules


1:30:36 AM [vite-plugin-svelte] /app/node_modules/@rgossiaux/svelte-headlessui/components/dialog/Dialog.svelte:2:11 Dialog has unused export property 'DialogStates'. If it is for external reference only, please consider using `export const DialogStates`
1:30:36 AM [vite-plugin-svelte] /app/node_modules/@rgossiaux/svelte-headlessui/components/disclosure/Disclosure.svelte:3:11 Disclosure has unused export property 'DisclosureStates'. If it is for external reference only, please consider using `export const DisclosureStates`
1:30:37 AM [vite-plugin-svelte] /app/node_modules/@rgossiaux/svelte-headlessui/components/listbox/Listbox.svelte:1:37 Listbox has unused export property 'ListboxStates'. If it is for external reference only, please consider using `export const ListboxStates`
1:30:37 AM [vite-plugin-svelte] /app/node_modules/@rgossiaux/svelte-headlessui/components/menu/Menu.svelte:9:11 Menu has unused export property 'MenuStates'. If it is for external reference only, please consider using `export const MenuStates`
1:30:37 AM [vite-plugin-svelte] /app/node_modules/@rgossiaux/svelte-headlessui/components/popover/Popover.svelte:1:37 Popover has unused export property 'PopoverStates'. If it is for external reference only, please consider using `export const PopoverStates`
1:30:37 AM [vite-plugin-svelte] /app/node_modules/@rgossiaux/svelte-headlessui/components/transitions/TransitionRoot.svelte:1:37 TransitionRoot has unused export property 'TreeStates'. If it is for external reference only, please consider using `export const TreeStates`
1:30:37 AM [vite-plugin-svelte] /app/node_modules/@rgossiaux/svelte-headlessui/internal/StackContextProvider.svelte:1:37 StackContextProvider has unused export property 'StackMessage'. If it is for external reference only, please consider using `export const StackMessage`
1:30:37 AM [vite-plugin-svelte] /app/node_modules/@rgossiaux/svelte-headlessui/utils/Render.svelte:21:11 Render has unused export property 'RenderStrategy'. If it is for external reference only, please consider using `export const RenderStrategy`
1:30:37 AM [vite-plugin-svelte] /app/node_modules/@rgossiaux/svelte-headlessui/utils/Render.svelte:3:11 Render has unused export property 'Features'. If it is for external reference only, please consider using `export const Features`
1:30:39 AM [vite-plugin-svelte] /app/node_modules/@rgossiaux/svelte-headlessui/components/dialog/Dialog.svelte:2:11 Dialog has unused export property 'DialogStates'. If it is for external reference only, please consider using `export const DialogStates`
1:30:39 AM [vite-plugin-svelte] /app/node_modules/@rgossiaux/svelte-headlessui/components/disclosure/Disclosure.svelte:3:11 Disclosure has unused export property 'DisclosureStates'. If it is for external reference only, please consider using `export const DisclosureStates`
1:30:39 AM [vite-plugin-svelte] /app/node_modules/@rgossiaux/svelte-headlessui/components/listbox/Listbox.svelte:1:37 Listbox has unused export property 'ListboxStates'. If it is for external reference only, please consider using `export const ListboxStates`
1:30:40 AM [vite-plugin-svelte] /app/node_modules/@rgossiaux/svelte-headlessui/components/popover/Popover.svelte:1:37 Popover has unused export property 'PopoverStates'. If it is for external reference only, please consider using `export const PopoverStates`
1:30:40 AM [vite-plugin-svelte] /app/node_modules/@rgossiaux/svelte-headlessui/components/menu/Menu.svelte:9:11 Menu has unused export property 'MenuStates'. If it is for external reference only, please consider using `export const MenuStates`
1:30:41 AM [vite-plugin-svelte] /app/node_modules/@rgossiaux/svelte-headlessui/components/transitions/TransitionRoot.svelte:1:37 TransitionRoot has unused export property 'TreeStates'. If it is for external reference only, please consider using `export const TreeStates`
1:30:41 AM [vite-plugin-svelte] /app/node_modules/@rgossiaux/svelte-headlessui/internal/StackContextProvider.svelte:1:37 StackContextProvider has unused export property 'StackMessage'. If it is for external reference only, please consider using `export const StackMessage`
1:30:41 AM [vite-plugin-svelte] /app/node_modules/@rgossiaux/svelte-headlessui/utils/Render.svelte:21:11 Render has unused export property 'RenderStrategy'. If it is for external reference only, please consider using `export const RenderStrategy`
1:30:41 AM [vite-plugin-svelte] /app/node_modules/@rgossiaux/svelte-headlessui/utils/Render.svelte:3:11 Render has unused export property 'Features'. If it is for external reference only, please consider using `export const Features`
```

**Comment by rgossiaux** [comment]
Thanks for the report! I see this as well.

This is due to the same issue as here: https://github.com/sveltejs/language-tools/issues/573 The library uses a bunch of different `export enum` statements, and it looks like TypeScript transpilation ends up producing code that generates these warnings. The linked issue just silenced the warnings in the language tools, but that doesn't help other parts of the ecosystem like vite-plugin-svelte. It feels to me like the transpilation process needs to be fixed to not produce Svelte code that will generate a warning. I'm not sure which tool should ultimately be responsible for fixing this, so I'll poke around and see what we can do.

In the meantime, it's completely safe to ignore these; they're a false positive. Sorry for the spam!

**Comment by rgossiaux** [comment]
Just as an FYI to anyone following this thread--because I personally find this super annoying, especially in the REPL, so I imagine you folks do too--I submitted a PR to Svelte itself that would fix these warnings. So far the maintainer response has been positive so I'm optimistic it could land within the next few weeks. Thanks for your patience!

**Comment by vhscom** [comment]
I saw two members already looked at the PR. Hopefully a maintainer will have a chance to get to it soon. Thanks for tackling that issue, @rgossiaux, as it creeps up in playwrite runs too and I'm about to `>/dev/null` 😆

**Comment by mfilteau** [comment]
Is it the same issue with these warnings?

[vite-plugin-svelte] ./node_modules/@rgossiaux/svelte-headlessui/components/dialog/Dialog.svelte:2:11 Dialog has unused export property 'DialogStates'. If it is for external reference only, please consider using `export const DialogStates`
[vite-plugin-svelte] ./node_modules/@rgossiaux/svelte-headlessui/components/disclosure/Disclosure.svelte:3:11 Disclosure has unused export property 'DisclosureStates'. If it is for external reference only, please consider using `export const DisclosureStates`
[vite-plugin-svelte] ./node_modules/@rgossiaux/svelte-headlessui/components/listbox/Listbox.svelte:1:37 Listbox has unused export property 'ListboxStates'. If it is for external reference only, please consider using `export const ListboxStates`
[vite-plugin-svelte] ./node_modules/@rgossiaux/svelte-headlessui/components/menu/Menu.svelte:9:11 Menu has unused export property 'MenuStates'. If it is for external reference only, please consider using `export const MenuStates`
[vite-plugin-svelte] ./node_modules/@rgossiaux/svelte-headlessui/components/popover/Popover.svelte:1:37 Popover has unused export property 'PopoverStates'. If it is for external reference only, please consider using `export const PopoverStates`
[vite-plugin-svelte] ./node_modules/@rgossiaux/svelte-headlessui/internal/StackContextProvider.svelte:1:37 StackContextProvider has unused export property 'StackMessage'. If it is for external reference only, please consider using `export const StackMessage`
[vite-plugin-svelte] ./node_modules/@rgossiaux/svelte-headlessui/utils/Render.svelte:21:11 Render has unused export property 'RenderStrategy'. If it is for external reference only, please consider using `export const RenderStrategy`
[vite-plugin-svelte] ./node_modules/@rgossiaux/svelte-headlessui/utils/Render.svelte:3:11 Render has unused export property 'Features'. If it is for external reference only, please consider using `export const Features`
[vite-plugin-svelte] ./node_modules/@rgossiaux/svelte-headlessui/components/transitions/common.svelte:4:11 Common has unused export property 'TreeStates'. If it is for external reference only, please consider using `export const TreeStates`

**Comment by rgossiaux** [comment]
After a long wait, Svelte 3.46.5 was just released today, which contains a fix for this issue that I submitted myself.

You can upgrade Svelte to 3.46.5 and these warnings should finally go away!

**Comment by vhscom** [comment]
Wow, just test this out. Big difference. Very nice. Great work on both the library and addressing that persnickety challenge, @rgossiaux. 🎉
