### ISSUE TITLE
<TransitionRoot> is not a valid SSR component.

### ISSUE THREAD

**Issue by jeetrex** [rgossiaux/svelte-headlessui#44]
Hi,

New to svelte here. I tried using one of TailwindUI components and got the error below.

TransitionRoot is not a valid SSR component. You may need to review your build config to ensure that dependencies are compiled, rather than imported as pre-compiled modules

**Comment by rgossiaux** [comment]
From https://github.com/sveltejs/sapper/issues/774 it looks like the library might need to be installed as a devDependency. Can you try that and see if it fixes your issue?

Just to make sure, are you using the right component? The public interface for transitions is `<Transition>` and `<TransitionChild>`

If neither of those is the issue, it'd be great if you could create a repository that reproduces this so I can investigate more-- hard to debug these build issues without it.

**Comment by jeetrex** [comment]
Looks like I was using the incorrect component.
