### ISSUE TITLE
Additional insert of empty `<div>` tag is throwing off my CSS element sizing.

### ISSUE THREAD

**Issue by twobitunicorn** [rgossiaux/svelte-headlessui#54]
Hey all,  I have a TransitionChild that contains a `<div>` tag with a class something downs the line of `class="relative flex-1 flex flex-col max-w-xs w-full pt-5 pb-4 bg-purple-700"`.  However, when I run this the sizing is all off.   I have found that in the inspection there is an additional `<div>` tag insterted before the body of a `TransitionChild`  with `class= " "`.  This additional div is throwing off my css and the resizing.  Is this the expected behaviour and I should work around this?  Or is this a bug that needs to get addressed?

**Comment by rgossiaux** [comment]
Can you share the relevant code?

**Comment by twobitunicorn** [comment]
@rgossiaux Yes, working on it.

**Comment by twobitunicorn** [comment]
`<script>
	const navigation = [
		{ name: 'Dashboard', href: '#' },
		{ name: 'Team', href: '#' },
		{ name: 'Projects', href: '#' }
	];

	import { Dialog, DialogOverlay, Transition, TransitionChild } from '@rgossiaux/svelte-headlessui';

	let isOpen = false;
</script>

<button
	type="button"
	on:click={() => (isOpen = !isOpen)}
	class="m-12 px-4 py-2 text-base font-medium leading-6 text-gray-700 transition duration-150 ease-in-out bg-white border border-gray-300 rounded-md shadow-sm hover:text-gray-500 focus:outline-none focus:border-blue-300 focus:shadow-outline-blue sm:text-sm sm:leading-5">
	Toggle!
</button>

<div>
	<Transition show={isOpen}>
		<Dialog class="fixed inset-0 flex z-40 md:hidden" onClose={() => (isOpen = false)}>
			<TransitionChild
				enter="transition-opacity ease-linear duration-300"
				enterFrom="opacity-0"
				enterTo="opacity-100"
				leave="transition-opacity ease-linear duration-300"
				leaveFrom="opacity-100"
				leaveTo="opacity-0">
				<DialogOverlay class="fixed inset-0 bg-gray-600 bg-opacity-75" />
			</TransitionChild>
			<TransitionChild
				enter="transition ease-in-out duration-300 transform"
				enterFrom="-translate-x-full"
				enterTo="translate-x-0"
				leave="transition ease-in-out duration-300 transform"
				leaveFrom="translate-x-0"
				leaveTo="-translate-x-full">
				<div class="relative flex-1 flex flex-col max-w-xs w-full pt-5 pb-4 bg-indigo-700">
					<TransitionChild
						enter="ease-in-out duration-300"
						enterFrom="opacity-0"
						enterTo="opacity-100"
						leave="ease-in-out duration-300"
						leaveFrom="opacity-100"
						leaveTo="opacity-0">
						<div class="absolute top-0 right-0 -mr-12 pt-2">
							<button
								type="button"
								class="ml-1 flex items-center justify-center h-10 w-10 rounded-full focus:outline-none focus:ring-2 focus:ring-inset focus:ring-white"
								on:click={() => (isOpen = false)}>
								<span class="sr-only">Close sidebar</span>
								<svg
									xmlns="http://www.w3.org/2000/svg"
									class="h-6 w-6"
									fill="none"
									viewBox="0 0 24 24"
									stroke="currentColor">
									<path
										stroke-linecap="round"
										stroke-linejoin="round"
										stroke-width="2"
										d="M6 18L18 6M6 6l12 12" />
								</svg>
							</button>
						</div>
					</TransitionChild>
					<div class="flex-shrink-0 flex items-center px-4">
						<img
							class="h-8 w-auto"
							src="https://tailwindui.com/img/logos/workflow-logo-indigo-300-mark-white-text.svg"
							alt="Workflow" />
					</div>
					<div class="mt-5 flex-1 h-0 overflow-y-auto">
						<nav class="px-2 space-y-1">
							{#each navigation as item}
								<a
									key={item.name}
									href={item.href}
									class="	bg-indigo-800 text-white
										group flex items-center px-2 py-2 text-base font-medium rounded-md">
									<svg
										xmlns="http://www.w3.org/2000/svg"
										class="mr-4 flex-shrink-0 h-6 w-6 text-indigo-300"
										fill="none"
										viewBox="0 0 24 24"
										stroke="currentColor">
										<path
											stroke-linecap="round"
											stroke-linejoin="round"
											stroke-width="2"
											d="M21 13.255A23.931 23.931 0 0112 15c-3.183 0-6.22-.62-9-1.745M16 6V4a2 2 0 00-2-2h-4a2 2 0 00-2 2v2m4 6h.01M5 20h14a2 2 0 002-2V8a2 2 0 00-2-2H5a2 2 0 00-2 2v10a2 2 0 002 2z" />
									</svg>
									{item.name}
								</a>
							{/each}
						</nav>
					</div>
				</div>
			</TransitionChild>
			<div class="flex-shrink-0 w-14" aria-hidden="true" />
		</Dialog>
	</Transition>
</div>`

**Comment by rgossiaux** [comment]
Thanks.

The empty div tags come from the transitions--each `<Transition>` and `<TransitionChild>` component renders exactly one div. In the React/Vue versions you have the ability to do `as={Fragment}` to not render anything and have the transition classes applied to the child component, but that's impossible to do directly in Svelte and would need some kind of more elaborate workaround (like exposing a [prop getter](https://kentcdodds.com/blog/how-to-give-rendering-control-to-users-with-prop-getters) or maybe for transitions an action which you could apply). At that point I'm not sure the increase in complexity is worth it.

The main downside is just when converting Tailwind UI snippets, I think. In cases where they use `as={Fragment}` you might need to pull some of the CSS classes up to the `<Transition>` / `<TransitionChild>`. In your case, try adding a `class=` prop to the problematic transition and duplicating or replacing some of the classes there. 

Looking at your snippet, if the problematic element is the `                <div class="relative flex-1 flex flex-col max-w-xs w-full pt-5 pb-4 bg-indigo-700">
`, you can just remove that div and move all of its classes to the parent `<TransitionChild>`.

**Comment by twobitunicorn** [comment]
@rgossiaux Cool, thanks!  I had the feeling that was gonna be the case but I wanted to check in before I committed.  Thanks again for your awesome work.
