### ISSUE TITLE
A REPL link in project description instead of the React one?

### ISSUE THREAD

**Issue by frederikhors** [rgossiaux/svelte-headlessui#56]
Thanks for the great job you have done so far.

I think a [REPL](https://svelte.dev/repl/hello-world) would be needed for a demo of all components.

The [link](https://headlessui.dev) in the description is not true because it shows the site with the React/Vue components.

**Comment by rgossiaux** [comment]
Thanks. I'm working on Svelte-specific documentation already which will include examples.

Duplicate of #23
