### ISSUE TITLE
Dialog is not removed and becomes unresponsive upon navigation.

### ISSUE THREAD

**Issue by ambiguous48** [rgossiaux/svelte-headlessui#68]
**Describe the bug**
Wrapping a Modal (a `Transition` & `Dialog`) in a `<div>`, makes it behave unexpectedly when navigating. Try opening the "bad" modal in my example, then either clicking your browser's back or forward button, or the "navigate away" button. The modal will not be removed. Also, it becomes unresponsive. The only way to remove it is to refresh the page.

The "good" modal behaves as expected.

**To Reproduce**
Minimal reproduction:
Repo: https://github.com/ambiguous48/modal-issue-2
Live version: https://modal-issue-2.vercel.app/

**Library version**
1.0.0-beta.9

**Comment by rgossiaux** [comment]
Thanks for the report! I cut a new release with the fix (v1.0.0-beta.10) since this is a pretty nasty bug.
