### ISSUE TITLE
Would it be possible to support Fragment?

### ISSUE THREAD

**Issue by msdrigg** [rgossiaux/svelte-headlessui#69]
I saw your discussion in #54 that you can't support fragment because of svelte limitations, but would it not be possible to do this with `<svelte:fragment>`?

I see the relevant code in `Render.svelte` is here:

https://github.com/rgossiaux/svelte-headlessui/blob/f5875ef8109267c8cc3d4b1159458dd7fd5fcb27/src/lib/utils/Render.svelte#L62

Could you create a custom component type called `Fragment` that could be imported like `import {Fragment} from '@rgossiaux/svelte-headlessui';`

Then use this fragment component by replacing this section: https://github.com/rgossiaux/svelte-headlessui/blob/f5875ef8109267c8cc3d4b1159458dd7fd5fcb27/src/lib/utils/Render.svelte#L93-L104

with this:

```html
{#if show}
  {#if element === Fragment}
    <svelte:fragment
      bind:el
      use={[...use, forwardEvents]}
      {...$$restProps}
      {...propsWeControl}
      hidden={hidden || undefined}
    >
      <slot />
    </svelte:fragment>
  {:else}
    <svelte:component
      this={element}
      bind:el
      use={[...use, forwardEvents]}
      {...$$restProps}
      {...propsWeControl}
      hidden={hidden || undefined}
    >
      <slot />
    </svelte:component>
  {/if}
{/if}
```

I am not a svelte expert and this is an untested idea, but if you think the idea could work, then I can write up a pr

**Comment by rgossiaux** [comment]
No, that doesn't work. `<svelte:fragment>` can't take props, and it doesn't have an element to bind to or to listen to events on.

The React and Vue libraries don't actually render a fragment. Instead they clone their children (using [cloneElement() in React](https://reactjs.org/docs/react-api.html#cloneelement) and [cloneVNode](https://vuejs.org/api/render-function.html#clonevnode) in Vue), throwing an error if there's more than one child, and then pass the needed props to this cloned child.

There is no API to do this in Svelte right now, and as far as I'm aware, there's no real workaround either.
