### ISSUE TITLE
[New Component] Combobox (Autocomplete)

### ISSUE THREAD

**Issue by The-Real-Thisas** [rgossiaux/svelte-headlessui#83]
I'm not sure if your aware but they recently added this combobox.

<img width="421" alt="Screen Shot 2022-03-15 at 3 44 09 PM" src="https://user-images.githubusercontent.com/59698123/158370999-213a2acf-9893-4058-939c-72788ea65711.png">

Would appreciate it being added as I think it's quite useful.

**Comment by bryanmylee** [comment]
Already an issue #63.

**Comment by The-Real-Thisas** [comment]
My mistake @bryanmylee, I did search for a previous issue but I must have made some mistake. Closing this due to duplication.
