### ISSUE TITLE
How to move a label out of a component

### ISSUE THREAD

**Issue by vkurko** [rgossiaux/svelte-headlessui#87]
I want to make a component containing two listboxes and one label. When the label is clicked, the first listbox should be focused.

![image](https://user-images.githubusercontent.com/1073174/163715085-024a20ca-4ca8-4b45-a72d-e83fae66c274.png)

But in the current implementation, a label can only be placed inside a listbox. If I make my own label then I have no way to bind it to the id of the first listbox because the id is unknown from outside the listbox component.

Is there any solution?

**Comment by ambiguous48** [comment]
I haven't tried this, but can you use an [action](https://svelte-headlessui.goss.io/docs/general-concepts#using-svelte-actions) to [set](https://developer.mozilla.org/en-US/docs/Web/API/Element/setAttribute) the [`aria-labelledby`](https://svelte-headlessui.goss.io/docs/listbox#listboxlabel) attribute?

Label:
`myLabel.setAttribute("for", "mylistbox");`

Element:
`myListbox.setAttribute("aria-labelledby", "mylistbox");`

**Comment by rgossiaux** [comment]
> I haven't tried this, but can you use an [action](https://svelte-headlessui.goss.io/docs/general-concepts#using-svelte-actions) to [set](https://developer.mozilla.org/en-US/docs/Web/API/Element/setAttribute) the [`aria-labelledby`](https://svelte-headlessui.goss.io/docs/listbox#listboxlabel) attribute?
> 
> Label: `myLabel.setAttribute("for", "mylistbox");`
> 
> Element: `myListbox.setAttribute("aria-labelledby", "mylistbox");`

I wouldn't recommend this; the components manage the aria properties themselves and I think it's best not to fight that. 

The intended way of handling this is to just use the `<ListboxLabel>` component for your label. It does need to be inside the `<Listbox>` component, but the `<Listbox>` is just a wrapper. There's an example in the docs, actually: https://svelte-headlessui.goss.io/docs/listbox#using-a-custom-label

**Comment by vkurko** [comment]
> It does need to be inside the `<Listbox>` component, but the `<Listbox>` is just a wrapper.

That's the problem! The current implementation does not allow the label to be moved outside of the wrapper. This greatly complicates the styling of components consisting of several fields, as in my case.

Or take bootstrap for example - it's layout for inline forms assumes that the label and the field are in different wrappers.

![image](https://user-images.githubusercontent.com/1073174/163965866-ba55461d-5918-431a-bbee-fe994013563d.png)

**Comment by vkurko** [comment]
@rgossiaux Closing the ticket does not mean there is no problem.

**Comment by rgossiaux** [comment]
> @rgossiaux Closing the ticket does not mean there is no problem.

With all due respect, I don't see any problem here. It just looks to me like you have some misunderstanding. Just put your label inside the `<Listbox>` wrapper, I don't understand what the issue is with that.

This is a free project so I don't have the bandwidth to debug your code--and doubly so for folks who are rude to me.

**Comment by vkurko** [comment]
> > @rgossiaux Closing the ticket does not mean there is no problem.
> 
> With all due respect, I don't see any problem here. It just looks to me like you have some misunderstanding. Just put your label inside the `<Listbox>` wrapper, I don't understand what the issue is with that.
> 
> This is a free project so I don't have the bandwidth to debug your code--and doubly so for folks who are rude to me.

You don't understand the issue, so you closed the ticket. I say the problem does exist and try to explain. You say I'm rude. Great logic :smile:
