### ISSUE TITLE
Dialog unmounted when unmount={false}

### ISSUE THREAD

**Issue by vhscom** [rgossiaux/svelte-headlessui#89]
**Describe the bug**
I'm unable to set `initialFocus` for a dialog component dynamically while using `unmount` prop with a value of `false`. Inspecting the source I can see the portal root is destroyed regardless of the `unmount` setting. As a result, the focus target no longer exists in the DOM when the dialog is restored.

I've also noticed `unmount` and `static` values to not appear as options within VSCode IntelliSense.

**To Reproduce**
The issue can be seen at the `/calendar` route of the following repo:
https://github.com/vhscom/svelte-headlessui-starter

Detailed steps:
To reproduce pull down the repo, install dependencies, navigate to the `/calendar` page, click `Add event` then choose one of the two `Pick` buttons within the dialog component. Inspect the DOM during this process and observe the "portal" is destroyed. Then open the `AddEventDialog` component and set `unmount={false}` for the dialog component and repeat. You will see the dialog is destroyed along with the portal root as opposed to being hidden as described in the docs.

**Library version**
`^1.0.0-beta.12`

**Comment by vhscom** [comment]
Here is a pictorial representation of the `/calendar` route, dialog and pick buttons referenced in OP:

<img width="839" alt="Screen Shot 2022-04-20 at 9 42 32 PM" src="https://user-images.githubusercontent.com/97140109/164244298-349a4baa-37b5-487e-a247-e5a4201d6aa1.png">

**Comment by rgossiaux** [comment]
Can you try to create a minimal reproduction? The `unmount` prop seems to work fine eg here: https://svelte.dev/repl/b0dc3f18ad024352ab0bf35a40d9b636?version=3.48.0

Your repo is pretty large and I don't have the bandwidth right now to do a deep dive into it just to understand the report.

**Comment by vhscom** [comment]
Must be something on my end then. I'll look into it and reopen if necessary. Thank you.

**Comment by rgossiaux** [comment]
Btw, re:

>I've also noticed unmount and static values to not appear as options within VSCode IntelliSense.

I just released 1.0.0 which includes some big typescript changes that had just been sitting around unreleased for a while. Give it a try and let me know if that fixes the autocomplete.

**Comment by vhscom** [comment]
Re: Btw. Just tested it out and works perfectly. 💯
