### ISSUE TITLE
Prefetch erroring on MenuItem with Href

### ISSUE THREAD

**Issue by vhscom** [rgossiaux/svelte-headlessui#95]
**Describe the bug**
Just started seeing this with [kit version 440](https://github.com/sveltejs/kit/blob/master/packages/kit/CHANGELOG.md#100-next340) and above. When I create a `MenuItem` like:

```svelte
<MenuItem
  href="/account/signin"
  sveltekit:prefetch
  class={({ active }) =>
    classes(
      active ? 'bg-gray-100 dark:bg-gray-800' : '',
      'block px-4 py-2 text-sm text-gray-700 dark:text-white'
    )}
>
  Sign in
</MenuItem>
```

I receive a type error on `sveltekit:prefetch` now whereas before sveltekit beta 440 I did not:

```term
Error: Type '{ href: string; "sveltekit:prefetch": true; class: ({ active }: { active: boolean; disabled: boolean; }) => string; }' is not assignable to type 'IntrinsicAttributes & Omit<TRenderProps<{ active: boolean; disabled: boolean; }, SupportedAs, "a">, "as" | TInternalProps | "static" | "unmount"> & { ...; } & { ...; }'.
  Property 'sveltekit:prefetch' does not exist on type 'IntrinsicAttributes & Omit<TRenderProps<{ active: boolean; disabled: boolean; }, SupportedAs, "a">, "as" | TInternalProps | "static" | "unmount"> & { ...; } & { ...; }'. (ts)
```

**To Reproduce**
Please share one of:
* A REPL using https://svelte.dev/repl/ (you can import from "@rgossiaux/svelte-headlessui" there and it will install from npm)
* A git repository which reproduces the issue: https://github.com/vhscom/svelte-headlessui-starter
* A full code snippet which reproduces the issue (see `GlobalNav` file in above repo)

**EDIT:** Disclosure buttons also seem to be affected. I ended up dropping the prefetches so I could ship the latest SK at the expense of performance for now. Here's [the specific commit](https://github.com/vhscom/svelte-headlessui-starter/commit/2bebdcb154d8c9204fe73bbe29d3fa99564c91cf#diff-96087a88d2518cfc9071ae78fd4fe848d15c7b49da67b6ee23e3a017af80d263) showing the removal of the `sveltekit:prefetch` and could be used to reproduce the issue by restoring one of the dropped attributes for `MenuItem` or the `DisclosureButton`.

**Library version**
Add the version of `svelte-headlessui` that you are using here.

```
@rgossiaux/svelte-headlessui@1.0.1
```

**Comment by vhscom** [comment]
Additionally, I see a related type issue for this snippet in the same `GlobalNav` file:

```svelte
<DisclosureButton
  key={name}
  as="a"
  {href}
  sveltekit:prefetch
  class={classes(
    current ? 'bg-gray-900 text-white' : 'text-gray-300 hover:bg-gray-700 hover:text-white',
    'block px-3 py-2 rounded-md text-base font-medium'
  )}
  aria-current={current ? 'page' : undefined}
>
  {name}
</DisclosureButton>
```

Here the error is a bit different but it started at the same time:

```
Error: Type '{ key: string; as: "a"; href: string; "sveltekit:prefetch": true; class: string; "aria-current": "page"; }' is not assignable to type 'IntrinsicAttributes & Omit<TRenderProps<{ open: boolean; close: (focusableElement: HTMLElement) => void; }, "a", "button">, "as" | ... 2 more ... | "unmount"> & { ...; } & { ...; }'.
  Property 'key' does not exist on type 'IntrinsicAttributes & Omit<TRenderProps<{ open: boolean; close: (focusableElement: HTMLElement) => void; }, "a", "button">, "as" | ... 2 more ... | "unmount"> & { ...; } & { ...; }'. (ts)
```

**Comment by rgossiaux** [comment]
Thanks for the report! This should be fixed in 1.0.2 now.

**Comment by vhscom** [comment]
Fix confirmed.

**Comment by vhscom** [comment]
Fix confirmed. Thanks!
